# Generated by Django 4.2.7 on 2025-12-22 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('project', models.CharField(default='General', max_length=100)),
                ('domain', models.CharField(default='General', max_length=100)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('difficulty', models.IntegerField(default=5)),
                ('estimated_effort', models.FloatField(default=1.0)),
                ('importance', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority_score', 'created_at'],
            },
        ),
    ]
